### ISSUE TITLE
New page: SDash tutorial

### ISSUE THREAD

**Issue by eidens** [source-data/sdash#253]
@HannahSonntag has prepared a tutorial for interacting with SDash. This is supposed to go in a new page on the website, with a link to it on the `About` page (or as a new primary navigation link?).

**Comment by HannahSonntag** [comment]
The draft for the tutorial is found in Teams: 
SourceData general in files> General > SDash > SDash beta testing > SDash_quick_tutorial_draft

**Comment by eidens** [comment]
Should be completed.
