### ISSUE TITLE
Redesign: display more content on screen

### ISSUE THREAD

**Issue by eidens** [source-data/sdash#287]
Currently there's a lot of empty space in the implemented redesign. In the panel grid view, there are also not many rows of panels visible.

There should be less empty space and more content visible, especially on bigger screens.

**Comment by eidens** [comment]
There should now be much more content and less empty space in the layout.

**Comment by HannahSonntag** [comment]
I think this looks all good and its nice we have more content on the dashboard. 
Will close this issue.
