### ISSUE TITLE
Edit authors: replace tooltip on close button with confirm modal

### ISSUE THREAD

**Issue by eidens** [source-data/sdash#288]
Currently, when the user adds/removes/edits an author of a panel, they can close the edit author modal with a single click on the cancel or close button. While there is a tooltip that warns users when hovering over the close button, we need an additional confirmation step before discarding a user's input like that.

**Comment by HannahSonntag** [comment]
I think its now very safe that one does not accidentally closes the edit author window w/o saving. Its a good solution!
