### ISSUE TITLE
In group grid page: Indicator that group is public

### ISSUE THREAD

**Issue by HannahSonntag** [source-data/sdash#293]
In the group grid page , there’s no indicator wether a group is public. 
There is an indicator in the filter sidebar, however. The same indicator should be used in the grid page. I indicated in the screenshot where it could go. 

<img width="276" alt="Screenshot 2021-12-31 at 08 59 35" src="https://user-images.githubusercontent.com/56673511/147811197-747de697-321f-4350-a3b8-d116a8fd726b.png">
<img width="747" alt="Screenshot 2021-12-31 at 08 59 51" src="https://user-images.githubusercontent.com/56673511/147811200-4ea87930-dc38-4707-8578-985888b4406f.png">

**Comment by eidens** [comment]
The "Unlocked" icon is now present on the group grid page if the corresponding group is public.
