### ISSUE TITLE
"Team page": Add acknowledgement for the dev team on the 'About' page.

### ISSUE THREAD

**Issue by HannahSonntag** [source-data/sdash#299]
Please include:

TL,TE,SP,OT and me! 
 similar to this:
![Screenshot 2022-01-19 at 17 01 44](https://user-images.githubusercontent.com/56673511/150168466-398ade05-7c6f-4b7c-9e1a-d6a61d0a68e2.png)

**Comment by Steve-MP** [comment]
Added in d4f56d2396978689a6d6f99b98bbc03ef725cd01
